GET http://localhost:3000/api/todos
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/todos/5c5ea519934275328d2321a5
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/todos/5c5ea519934275328d2321a5
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjg1YzAxZDhmZDFjM2RiYjk0ODYiLCJlbWFpbCI6ImFyaWVzZXB0aWFuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExMTMwMzc1NTAzNDEzMTk4NjEwNSIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkwOTczfQ.bWDLP7hxGcKIn-MmWyqEXVo11aJIA1llCUX2g9B4uvs

###
GET http://localhost:3000/api/todos/5c5ea519934275328d2321a5
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjhiZjAxZDhmZDFjM2RiYjk0ODciLCJlbWFpbCI6ImFzZXB0bkBnb29nbGVtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjEwMTYyOTY0MzQxMTY0MTkzNTE3NiIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkxMDcxfQ.pV6vk4Jx0GEzPKULijkhzNshtJ9rv70157injMXroG4

###
POST http://localhost:3000/api/todos
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=makan&description=makan nasi goreng&dueDate=2019-12-31&owner=nasi&status=unfinished

###
PUT http://localhost:3000/api/todos/5c5ea519934275328d2321a5
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=makan&description=makan nasi goreng&dueDate=2019-12-31&owner=nasi&status=unfinished

###
DELETE http://localhost:3000/api/todos/5c5ebb94573e794136049bb2
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/projects
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/projects
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjg1YzAxZDhmZDFjM2RiYjk0ODYiLCJlbWFpbCI6ImFyaWVzZXB0aWFuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExMTMwMzc1NTAzNDEzMTk4NjEwNSIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkwOTczfQ.bWDLP7hxGcKIn-MmWyqEXVo11aJIA1llCUX2g9B4uvs

###
GET http://localhost:3000/api/projects/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/projects/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjg1YzAxZDhmZDFjM2RiYjk0ODYiLCJlbWFpbCI6ImFyaWVzZXB0aWFuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExMTMwMzc1NTAzNDEzMTk4NjEwNSIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkwOTczfQ.bWDLP7hxGcKIn-MmWyqEXVo11aJIA1llCUX2g9B4uvs

###
GET http://localhost:3000/api/projects/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjhiZjAxZDhmZDFjM2RiYjk0ODciLCJlbWFpbCI6ImFzZXB0bkBnb29nbGVtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjEwMTYyOTY0MzQxMTY0MTkzNTE3NiIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkxMDcxfQ.pV6vk4Jx0GEzPKULijkhzNshtJ9rv70157injMXroG4

###
POST http://localhost:3000/api/projects
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=my project&description=my desc

###
PUT http://localhost:3000/api/projects/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=my project&description=my desc

###
DELETE http://localhost:3000/api/projects/5c5ebf101f7f8b4257cfe78a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
POST http://localhost:3000/api/todos/project/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=makan project&description=makan nasi goreng project&dueDate=2019-12-31&owner=nasi&status=unfinished

###
GET http://localhost:3000/api/todos/project/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/todos/project/5c5eb27b5c081c39085a90b1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNjg1YzAxZDhmZDFjM2RiYjk0ODYiLCJlbWFpbCI6ImFyaWVzZXB0aWFuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExMTMwMzc1NTAzNDEzMTk4NjEwNSIsIl9fdiI6MCwiaWF0IjoxNTQ5NjkwOTczfQ.bWDLP7hxGcKIn-MmWyqEXVo11aJIA1llCUX2g9B4uvs

###
POST http://localhost:3000/api/projects/member/5c5eb27b5c081c39085a90b1/arieseptian@gmail.com
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
DELETE http://localhost:3000/api/projects/member/5c5eb27b5c081c39085a90b1/5c5e685c01d8fd1c3dbb9486
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
POST http://localhost:3000/api/users/register
Content-Type: application/x-www-form-urlencoded

name=test&password=test&email=test@example.com

###
POST http://localhost:3000/api/users/login
Content-Type: application/x-www-form-urlencoded

password=test&email=test@example.com
